### ISSUE TITLE
Certificate has expired on Docs web page

### ISSUE THREAD

**Issue by Welkin-Totoro** [WFCD/api-spec#1]
I'm not sure if I should raise the issue here.
I got trouble visiting [https://docs.warframestat.us/](https://docs.warframestat.us/) today and found that the certificate of cdn.jsdelivr.net which 'redoc.standalone.js' downloading from has expired on 2019/4/20.

**Comment by Welkin-Totoro** [comment]
Certificate has been updated

**Comment by TobiTenno** [comment]
yeah, sorry, it was probably a time offset form where you live, the site's hosted on github, so they manage the cert for it.
