### ISSUE TITLE
Wrong Documentation

### ISSUE THREAD

**Issue by Mettwasser** [WFCD/api-spec#37]
https://docs.warframestat.us/#tag/Worldstate/operation/getCetusByPlatform
shows that the enpoint `https://api.warframestat.us/{platform}/cetusCycle` `active` and `startString` are given with the response - they are not

**Comment by TobiTenno** [comment]
are the missing fields marked as required?

**Comment by Mettwasser** [comment]
> are the missing fields marked as required?

omg no, sorry.
