### ISSUE TITLE
paths/*.yaml file is an invalid file name for Windows

### ISSUE THREAD

**Issue by software-2** [WFCD/api-spec#4]
`*.yaml` is an invalid filename on Windows. This prevents me from even checking out the repo in git.

To my knowledge, OAS doesn't support "global" responses like this as of 3.0.1. If you're using a non-standard build process, could you please include that in the readme so I can help contribute?

Also, it looks like none of the generated pages are actually including a 404 response, so this entire file isn't actually being utilized? For me, personally, I'm not sure how much value there is in having a generic 404 response listed for every endpoint. The easiest solution here may be to delete `*.yaml`?

**Comment by TobiTenno** [comment]
I don't use a non-standard build process, I simply don't build it in Windows.

**Comment by TobiTenno** [comment]
I'm changing it a bit to use an enum with single value `*` so it'll build on windows.

**Comment by TobiTenno** [comment]
closed with 38bfe8263fbe52c8f3bc991d1ec54dfd977b6af3
i'll have to decide later how i want to do this
